const { By, until, Key } = require('selenium-webdriver');
const TestHelper = require('./testHelper');
const config = require('./config');

async function testLostAndFound() {
  const helper = new TestHelper('Lost and Found');
  try {
    await helper.init();
    await helper.login(config.credentials.customer.email, config.credentials.customer.password);

    await helper.log('Navigating to Lost & Found');
    await helper.driver.get(`${config.baseUrl}/dashboard/lost-items`);

    await helper.log('Clicking "Report New Item"');
    const reportBtn = await helper.driver.wait(until.elementLocated(By.xpath("//button[contains(., 'Report New Item')]")), 10000);
    await reportBtn.click();

    await helper.log('Filling report details');
    await helper.driver.findElement(By.placeholderText('e.g. ORD-123456')).sendKeys('ORD-TEST-123');
    await helper.driver.findElement(By.placeholderText('e.g. Blue Cotton Shirt')).sendKeys('Selenium Test Shirt');
    await helper.driver.findElement(By.tagName('textarea')).sendKeys('This is a test report generated by Selenium.');

    await helper.log('Submitting report');
    await helper.driver.findElement(By.xpath("//button[contains(., 'Submit Report')]")).click();

    await helper.log('Verifying success message');
    await helper.driver.wait(until.elementLocated(By.xpath("//div[contains(., 'Report submitted successfully')]")), 10000);
    await helper.log('Lost and Found report submitted successfully', 'PASS');

  } catch (error) {
    await helper.log('Test Failed', 'FAIL', error.message);
  } finally {
    helper.generateHtmlReport();
    await helper.quit();
  }
}

async function testTrackOrder() {
  const helper = new TestHelper('Track Order');
  try {
    await helper.init();
    await helper.login(config.credentials.customer.email, config.credentials.customer.password);

    await helper.log('Navigating to Track Order');
    await helper.driver.get(`${config.baseUrl}/track-order`);

    await helper.log('Entering Tracking ID');
    const input = await helper.driver.findElement(By.placeholderText('e.g., ORD-001, ORD-002, ORD-003'));
    await input.sendKeys('ORD-001');

    await helper.log('Clicking Track Order');
    await helper.driver.findElement(By.xpath("//button[contains(., 'Track Order')]")).click();

    await helper.log('Verifying order details displayed');
    await helper.driver.wait(until.elementLocated(By.xpath("//h3[contains(., 'Order #ORD-001')]")), 10000);
    await helper.log('Track Order search successful', 'PASS');

  } catch (error) {
    await helper.log('Test Failed', 'FAIL', error.message);
  } finally {
    helper.generateHtmlReport();
    await helper.quit();
  }
}

async function testDryCleaning() {
  const helper = new TestHelper('Dry Cleaning');
  try {
    await helper.init();
    await helper.login(config.credentials.customer.email, config.credentials.customer.password);

    await helper.log('Navigating to Dry Cleaning');
    await helper.driver.get(`${config.baseUrl}/dashboard/dry-cleaning`);

    await helper.log('Selecting items');
    // Click '+' button for Suit (2-piece)
    const suitCard = await helper.driver.wait(until.elementLocated(By.xpath("//h4[contains(., 'Suit (2-piece)')]/following-sibling::div//button[2]")), 10000);
    await suitCard.click();

    await helper.log('Filling pickup details');
    const dateInput = await helper.driver.findElement(By.id('pickup-date'));
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 2);
    const dateStr = tomorrow.toISOString().split('T')[0];
    await dateInput.sendKeys(dateStr);

    const timeSelect = await helper.driver.findElement(By.tagName('select'));
    await timeSelect.sendKeys('10:00 AM - 11:00 AM');

    await helper.log('Filling address');
    await helper.driver.findElement(By.placeholderText('Street Address')).sendKeys('Selenium Test Street');
    await helper.driver.findElement(By.placeholderText('City')).sendKeys('Test City');
    await helper.driver.findElement(By.placeholderText('ZIP Code')).sendKeys('123456');

    await helper.log('Submitting form');
    await helper.driver.findElement(By.css('button[type="submit"]')).click();

    await helper.log('Verifying summary modal');
    await helper.driver.wait(until.elementLocated(By.xpath("//h3[contains(., 'Order Summary')]")), 10000);
    await helper.log('Dry Cleaning form submitted to summary', 'PASS');

  } catch (error) {
    await helper.log('Test Failed', 'FAIL', error.message);
  } finally {
    helper.generateHtmlReport();
    await helper.quit();
  }
}

async function testOrderHistory() {
  const helper = new TestHelper('Order History');
  try {
    await helper.init();
    await helper.login(config.credentials.customer.email, config.credentials.customer.password);

    await helper.log('Navigating to Payment History');
    await helper.driver.get(`${config.baseUrl}/dashboard/payment-history`);

    await helper.log('Searching for orders');
    const searchInput = await helper.driver.findElement(By.placeholderText('Search by Order ID or Service...'));
    await searchInput.sendKeys('ORD');

    await helper.log('Filtering by status');
    const statusSelect = await helper.driver.findElement(By.xpath("//select[contains(., 'All Statuses')]"));
    await statusSelect.sendKeys('Paid');

    await helper.log('Verifying filter results');
    // Check if table rows exist or "No transactions found" is NOT shown if there are orders
    await helper.log('Order History filtering tested', 'PASS');

  } catch (error) {
    await helper.log('Test Failed', 'FAIL', error.message);
  } finally {
    helper.generateHtmlReport();
    await helper.quit();
  }
}

async function testNotifications() {
  const helper = new TestHelper('Notifications');
  try {
    await helper.init();
    await helper.login(config.credentials.customer.email, config.credentials.customer.password);

    await helper.log('Navigating to Notifications');
    await helper.driver.get(`${config.baseUrl}/dashboard/notifications`);

    await helper.log('Checking for notifications');
    // Try to mark all as read if button is enabled
    const markAllBtn = await helper.driver.findElement(By.xpath("//button[contains(., 'Mark all as read')]"));
    if (await markAllBtn.isEnabled()) {
      await helper.log('Clicking Mark all as read');
      await markAllBtn.click();
    } else {
      await helper.log('No unread notifications to mark');
    }

    await helper.log('Notifications testing completed', 'PASS');

  } catch (error) {
    await helper.log('Test Failed', 'FAIL', error.message);
  } finally {
    helper.generateHtmlReport();
    await helper.quit();
  }
}

// Add placeholderText locator for selenium-webdriver if not present
By.placeholderText = function(text) {
  return By.xpath(`//*[@placeholder='${text}']`);
};

async function runAll() {
  console.log('Starting All User Module Tests...');
  await testLostAndFound();
  await testTrackOrder();
  await testDryCleaning();
  await testOrderHistory();
  await testNotifications();
  console.log('All tests completed.');
}

if (require.main === module) {
  runAll();
}

module.exports = {
  testLostAndFound,
  testTrackOrder,
  testDryCleaning,
  testOrderHistory,
  testNotifications,
  runAll
};
